#!/bin/bash

setup=`dirname $0`
logs=`dirname $setup`/logs

# sudo ln -i $setup/nginx /etc/nginx/sites-available/nginx
# sudo ln -i -s /etc/nginx/sites-available/nginx /etc/nginx/sites-enabled/nginx

# sudo nginx -s reload

cd $logs

# nohup online-text-flow server --path textflow   --port 5000          > 5000.log 2>&1 &
# nohup online-text-flow server --path textflow/1 --port 5001 en de cs > 5001.log 2>&1 &
# nohup online-text-flow server --path textflow/2 --port 5002 en fr it > 5002.log 2>&1 &
# nohup online-text-flow server --path textflow/3 --port 5003 cs en fr > 5003.log 2>&1 &

# nohup online-text-flow server --path elitr                 --port 6000 > 6000.log 2>&1 &
# nohup online-text-flow server --path elitr/sg1             --port 6001 > 6001.log 2>&1 &
# nohup online-text-flow server --path elitr/monday-seminars --port 6002 > 6002.log 2>&1 &

# nohup online-text-flow server --view https://www.youtube.com/embed/7cjia0L80dM --pass '' \
#                               --path elitr/theaitre        --port 6003 > 6003.log 2>&1 &

# nohup sudo online-text-flow server --view https://www.youtube.com/embed/7cjia0L80dM --pass '' \
#                                    --path elitr/theaitre --host 0.0.0.0 --port 80 > 80.log 2>&1 &

nohup sudo online-text-flow server --view 'https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fwww.facebook.com%2FTheaitre%2Fvideos%2F851406275425274%2F&show_text=false&width=560' \
                                   --pass '' en cs \
                                   --path elitr/theaitre --host 0.0.0.0 --port 80 > 80.log 2>&1 &

sleep 1

cd - > /dev/null

echo

# head $logs/[56]00[0-3].log

head $logs/80.log

echo
echo tail -f $logs/80.log
